#!/bin/bash
#
# Regression tests for the parsers.
#
# Below are a number of URLs followed by the agenda they contain. When
# calling agendabot with these URLs, it should reproduce exactly this
# output.

trap 'rm $TMP1 $TMP2 $EXCEPTIONS' 0
TMP1=`mktemp /tmp/test-XXXXXX` || exit 1
TMP2=`mktemp /tmp/test-XXXXXX` || exit 1

cat >$TMP2 <<EOF
agenda: https://lists.w3.org/Archives/Public/public-epub-wg/2022Feb/0000.html
clear agenda
agenda+ Review Privacy and Security PR [1]
agenda+ Updates to Obfuscation [2]
agenda+ Discuss Security feedback [3]

agenda: https://www.w3.org/events/meetings/d15352a9-86a0-44f4-ab19-7c4aad4d654b/20220309T090000
clear agenda
agenda+ Question about resolution on -> issue 110 https://github.com/w3c/audiobooks/issues/110
agenda+ PR: -> Correcting Errata and adding Change Log https://github.com/w3c/audiobooks/pull/111
agenda+ Charter Questions
agenda+ Requiring TOCs [ -> 1 https://github.com/w3c/audiobooks/issues/97 ] [ -> 2 https://github.com/w3c/audiobooks/issues/96 ]

agenda: https://www.w3.org/events/meetings/baf262b7-7551-4c04-96a0-662d85c35505/20220120T150000
clear agenda
agenda+ Agenda Review
agenda+ Action Items
agenda+ Info Share
agenda+ RADAR Review
agenda+ String-Meta
agenda+ Radar Assignments
agenda+ AOB?

agenda: https://lists.w3.org/Archives/Public/public-payments-wg/2022Jan/0049.html
clear agenda
agenda+ Proposal to address issue 125 (failed icon download)
agenda+ New issue 172: Opt-out link enhancement
agenda+ Next meeting: 7 February

agenda: https://www.w3.org/events/meetings/1d223877-730c-446f-bfa9-2e9222902112/20220203T130000
clear agenda
agenda+ -> New Issue Triage https://bit.ly/3ARvtLJ
agenda+ -> New PR Triage https://bit.ly/3s6LYzD
agenda+ -> Deep Dive planning https://bit.ly/aria-meaty-topic-candidates
agenda+ -> Figure out what to do with the DPUB mappings overlap with the ARIA Core spec, in the context of newer implementation differences https://github.com/w3c/aria/issues/1643
agenda+ -> Is this proposal overcome by events?: Updated spec text to reflect the processing of hidden elements when c… https://github.com/w3c/accname/pull/137
agenda+ -> Any updates?: Prohibit rowcount and rowindex on rows in treegrid and prohibit posinset and setsize on rows in tables and grids https://github.com/w3c/aria/issues/1303
agenda+ -> Any Updates?: When is hidden content taken into calculation of name and description? https://github.com/w3c/accname/issues/57
agenda+ -> Do we have any decisions?: Clarify usage of aria-haspopup https://github.com/w3c/aria/issues/1024
agenda+ -> Initial aria-textseparation (depends on generic PR being merged) https://github.com/w3c/aria/pull/996
agenda+ -> 1.3 Blocking issues https://github.com/w3c/aria/labels/1.3-Blocking

agenda: https://www.w3.org/events/meetings/54fb3c39-8826-418b-bcac-46e112f08535/20220203T090000
clear agenda
agenda+ Solid introduction and discussion (Raf Buyle + colleagues, 30 minutes presentation + 15 minutes discussion);
agenda+ OGC testbed results/demo in relation to WebVMT (Rob Smith, 10 minutes);
agenda+ Update of SDW Best Practices work + advertise next subgroup call (Timo Homburg, 5 minutes).

agenda: https://lists.w3.org/Archives/Public/public-did-wg/2022Jan/0001.html
clear agenda
agenda+ Agenda Review, Introductions  (5 min)
agenda+ Upcoming meeting schedule  (10 min)
agenda+ did:id Method [1] (15 min)
agenda+ did:keri Method [2] (25 min)

agenda: https://www.w3.org/events/meetings/1e1799a6-f588-4e61-badf-2f595f0cb2ec
clear agenda
agenda+ ISSUE: -> duration property when using t= fragment selectors https://github.com/w3c/audiobooks/issues/110
agenda+ ISSUE: -> Add note about the importance of adding the "duration" property to readingOrder items https://github.com/w3c/audiobooks/issues/108
agenda+ FEATURE REQUEST: -> Possible requirement for one image per track https://github.com/w3c/audiobooks/issues/106
agenda+ FEATURE REQUEST: -> Require the format and processing of the table of contents https://github.com/w3c/audiobooks/issues/97
agenda+ FEATURE REQUEST: -> Requirement for a table of contents https://github.com/w3c/audiobooks/issues/96
agenda+ FEATURE REQUEST: -> A standard rel value for the primary entry page https://github.com/w3c/audiobooks/issues/78
agenda+ FEATURE REQUEST: -> Deep Linking for Packaged Audiobooks https://github.com/w3c/audiobooks/issues/76
agenda+ FEATURE REQUEST: -> Add primary entry page to resources when not a publication resource https://github.com/w3c/audiobooks/issues/75
agenda+ FEATURE REQUEST: -> Create a vocabulary of rel attributes for extra resources https://github.com/w3c/audiobooks/issues/7
agenda+ ERRATA: -> duration property in JSON example uses incorrect syntax (number instead of ISO 8601 string format) https://github.com/w3c/audiobooks/issues/109

agenda: https://lists.w3.org/Archives/Public/w3c-wai-gl/2022JanMar/0059.html
clear agenda
agenda+ WCAG 3 Introduction to Status Level Marking https://rawgit.com/w3c/silver/status-indicators-new/guidelines/index.html#text-alternatives
agenda+ WCAG 3 Requirements https://www.w3.org/2002/09/wbs/35422/WCAG3_requirements/
agenda+ WCAG 2.2 Misc Issues https://www.w3.org/2002/09/wbs/35422/wcag22-misc/ (1st question new, based on last weeks’ discussion)
agenda+ WCAG 2.2 Focus appearance https://www.w3.org/2002/09/wbs/35422/wcag22-focus-appearance-enhanced2/ (opening later today)

agenda: https://lists.w3.org/Archives/Public/www-style/2022Feb/0000.html
clear agenda
agenda+ Extra agenda items and other digressions
agenda+ [css-ruby-1] Propose to treat rtc with orthogonal writing-mode to be inter-character rather than using ruby-position
agenda+ [css-inline][css-pseudo] Interaction of root inline box and ::first-line
agenda+ [css-highlight-api][css-contain] static ranges and css-contain
agenda+ [css-contain-3] Container Queries and pseudo elements
agenda+ [css-contain-3] Determine container type automatically from the query
agenda+ [css-contain] CQ vs shadow boundaries
agenda+ [css-conditional-4] Rename @when to @if
agenda+ [css-overflow] Proposing scroll-start: allowing overflow scroll to not always start at 0 on 1st layout pass

agenda: https://lists.w3.org/Archives/Public/public-web-adv/2022Jan/0009.html
clear agenda
agenda+ Introductions and Agenda Curation
agenda+ Federated Credential Management and the FedID CG (Kris Chapman)
agenda+ Topics API (Josh Karlin)
agenda+ Dashboard, planning upcoming agendas
agenda+ AOB

agenda: https://lists.w3.org/Archives/Public/public-webauthn-adoption/2022Feb/0000.html
clear agenda
agenda+ Accompanying developers in the passkeys journey (Tim, Matt)
agenda+ format for WebAuthn authenticator response output
agenda+ WebAuthn conformance check-in
agenda+ next meeting - Feb 21st is a US holiday, skip until March 7?

agenda: https://lists.w3.org/Archives/Public/public-xformsusers/2022Feb/0003.html
clear agenda
agenda+ ACTION-2309: Research xpath3 function definitions (Erik)
agenda+ ACTION-2315: Report on event handling in web components (Erik)
agenda+ ACTION-2312: Devise text for submission using @value (Steven)
agenda+ ACTION-2314: Compose text that matches the <control/> discussion for 
agenda+ ACTION-2313: Research the alternatives for 'dirty' data, and produce 
agenda+ Timescale Plans

agenda: https://lists.w3.org/Archives/Public/public-rdf-star/2022Feb/0000.html
clear agenda
agenda+ Announcements and newcomers
agenda+ Open actions
agenda+ WG chartering
agenda+ Open-ended discussions

agenda: https://lists.w3.org/Archives/Public/www-math/2022Feb/0002.html
clear agenda
agenda+ Announcements/Updates
agenda+ Plan for unifying/disunifying level 1 name. -- https://github.com/w3c/
agenda+ Progress on aliases for level 1 names? -- https://github.com/w3c/mathml

agenda: https://lists.w3.org/Archives/Public/public-epub3/2022Feb/0003.html
clear agenda
agenda+ Continue identifying important DPUB ARIA roles.
agenda+ How to group the DPUB ARIA roles for presenting them to ARIA WG?
agenda+ Next call?

agenda: https://lists.w3.org/Archives/Public/public-antifraud/2022Feb/0000.html
clear agenda
agenda+ Use Cases and Threat Models (15 mins)
agenda+ Charter Review (10 mins)
agenda+ Fraud Solution Providers - Socure (15 mins)
agenda+ Initial Work Items (15 mins)

agenda: https://lists.w3.org/Archives/Public/public-credentials/2022Jan/0245.html
clear agenda
agenda+ Agenda Review, Introductions, Relevant
agenda+ Start Workflow - Presentation Availability Convergence
agenda+ Workflow Interaction - Submit Presentation Convergence
agenda+ Issue Processing (as time allows)
agenda+ Any other business?

agenda: https://www.w3.org/events/meetings/b9d3fe3e-c3c1-4154-a26d-6b4be1137a9b/20220217T160000
clear agenda
agenda+ This meeting
agenda+ IMSC HRM
agenda+ Status on HR and WR
agenda+ Issues (including HR issues)
agenda+ Rechartering status update
agenda+ Dubbing and AD requirements
agenda+ AOB – please notify of any other AOB now!

agenda: https://www.w3.org/events/meetings/04ee1fba-d1a3-4473-98cb-0726ce44cb9c/20230720T150000/
clear agenda
agenda+ Agenda Review
agenda+ Action Items
agenda+ Info Share
agenda+ RADAR Review
agenda+ Pending Issue Review
agenda+ AOB?

agenda: https://www.w3.org/events/meetings/fc585baf-5661-44ac-8a81-c599d8ab81bb/20230725T220000/
clear agenda
agenda+ Agenda
agenda+ Action Items
agenda+ Info Share and Progress Reports
agenda+ Review on-going issues

agenda: https://www.w3.org/events/meetings/c5b143d1-0a5b-4adb-8d60-0f5f9bfe5a41/20230720T150000/
clear agenda
agenda+ Agenda Review
agenda+ Action Items
agenda+ Info Share
agenda+ RADAR Review
agenda+ Pending Issue Review
agenda+ Various Pull Requests
agenda+ AOB?

agenda: https://github.com/w3c/data-shapes/blob/agenda/admin/agenda-2025-06-09.md
clear agenda
agenda+ Announcements
agenda+ Topical PRs
agenda+ Decisions
agenda+ Discussion
agenda+ Process

EOF


perl agendabot.pl -v -m /dev/null -o $TMP1 \
     `grep -E '^agenda:' $TMP2 | cut -d' ' -f2-`

diff -u $TMP2 $TMP1 && echo OK || echo Errors found

